### ISSUE TITLE
sscanf not being checked for scan error in lpmd_util.c

### ISSUE THREAD

**Issue by ColinIanKing** [intel/intel-lpmd#52]
There is a sscanf() libc call that ignores error return codes, see src/lpmd_util.c, function: parse_proc_stat():

```
                 while (p != NULL) {
                        if (idx >= STAT_MAX)
                                break;

                        if (idx == STAT_CPU) {
                                idx++;
                                p = strtok (NULL, " ");
                                continue;
                        }

                        sscanf (p, "%llu", &info->stat[idx]);
                        p = strtok (NULL, " ");
                        idx++;
                }
```

..the sscanf for intfo->stat[idx] probably should be checked for a sane stat value being parsed. It's unlikely this can fail, but it's worth ensuring the sscanf'd data is valid and sane.

**Comment by zhang-rui** [comment]
In this case, sscanf can only return EOF, 0 and 1, and 1 is what we get on success, right?

Question: will info->stat[idx] be set when sscanf returns EOF or 0?
If no, that is what I want, because we can just ignore this failure, and the statistics will recover when parsing /proc/stat next time.

I agree we should check the return value, question is how to handle this failure?
Maybe we can give a warning message when it fails, or just a comment saying that we ignore the failure on purpose?
what do you think?

**Comment by zhang-rui** [comment]
Problem addressed in https://github.com/intel/intel-lpmd/pull/57
